# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'env'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if ($env:BUILD_REPOSITORY_ID -like "*github*") {
        Write-Host '("https://product-catalog-api-onees-prod-disco-east-us.prod.avalanch.es/products?artifactType=GitHub%2FRepository&artifactId=github://github.com/$env:BUILD_REPOSITORY_ID")' }
      else {
        Write-Host '("https://product-catalog-api-onees-prod-disco-east-us.prod.avalanch.es/products?artifactType=Scms.Git.Vsts&artifactId=vsts://$env:SYSTEM_COLLECTIONID/$env:SYSTEM_TEAMPROJECTID/$env:BUILD_REPOSITORY_ID")' }